
      import React, { Component } from 'react';
// import surf from './pictures/surf.jpg'
const blogContent= {
  border:"2px dotted black",
  padding: "10px",
  margin: '40px auto',
  fontSize: '1.38em',
   width:'100%',
   maxWidth:'900px',
  content:    `It’s time for IPV4 to step aside and let IPV6 take the wheel for global dominance of the internet. IPV4 has had its time. It’s been around for nearly 5 decades. It had had more than its fair share of dominance over the years. The internet needs to kick IpV4 to the curb, and for good reasons. The world is ready to discover what being connected to the internet really could be all about. The founders could never have imagined so many devices beyond the desktop computer to connect to. Since then, our refrigerators, wrist watches, doorbells, cellular phones, and perhaps pretty much everything; could be connected as well. After all, IPV6 has more addresses than grains of sand on the earth. Quintillion is a big number, and IPV6 available addresses; are several times that big. So literally giving everything its own address becomes a rational idea in that regard, all thanks to IPV6. IPV6 is not just superior in that way though. IPV6 is better than IPV4 through its routing capabilities, security and connectivity as well. IPV4 needs to do everyone a favor and go away.

IPV6 is the ultimate leader in addressing space. IPV6 puts IPV4’s 4.3 billion unique addresses to absolute shame. It really wasn’t the founders of the internet’s fault; Nobody could have predicted how far the internet would ultimately have become. Cell phones were a major turning point in the world of networking when they came out. Back in 2000, I remember sitting in the lecture hall at R.I.T. I was a New Media Design major at that time in my life. I was listening to the professor there, talking about the change that smart phones will have in the future. Boy was he right. Not long after that everyone had a smartphone to the point now that your common influencer has all the computing power of a Hollywood studio in their pocket. Well now, all those smart phones became the must have for literally everyone who wants to be anybody. This greatly expanded the size and number of networks. Now we have a population boom for internet addresses. Much to everyone’s disappoint; It wasn’t long before IPV4 would be shooting blanks. 

Networks are slow to jump on the bandwagon. The market was so saturated with IPV4 that it would have to take a severely united front to change the internet landscape. It would have taken an absolutely epic movement to fully switch over. Maybe when our desktop computers and laptops become a relic of the past, like coin operated public telephones; we can fully clean up the mess. That’s the only scenario I could imagine that would cut out all those weak IPV ties. I wouldn’t hold my breath for that day to come though. The networks, much like deranged stalkers, just simply don’t get the clue. IPV6 uses “hexadecimal” to fashion hextets resulting in 128-bit addresses. IPV4 uses octets that result in 32-bit addresses. IPV4 has run out of addresses by this point. So, the networks went the band aid route and split the addresses up using NAT (Network Address Translation). This is NAT cool. Splitting the connections up ends the coolest part of IPV6 before it can even begin; it’s end to end connection capability. Why break up a perfectly good connection when you have enough addresses through IPV6 already. The overhead expenses which come from splitting them just isn’t necessary. Networks need a reality check, or they must really trust everyone inside their fractured LAN (Local Area Network). I got news for them if they haven’t gotten the memo by now. NAT isn’t good security.

IPv6 also brings both organized and modern security to the table. Instead of hiding behind NAT and pretending that obscurity equals protection, IPV6 uses tools that actually secure the network. Router Advertisement Guard could block funky RA messages that try to hijack the default gateway. DHCPv6 Guard prevents rogue DHCP servers from poisoning the network with fake configurations. Redirect messages can be validated so devices don’t get tricked into sending traffic to the wrong place. All of this comes straight out of the Neighbor Discovery Protocol defined in RFC 4861, which gives IPv6 built in security instead of the band aid defenses IPV4 used. IPV6 is end to end connectivity. IPv6 doesn’t need to hide behind NAT. 

	IPV6 has changed our idea of what it’s like to connect over the internet. IPV6’s addressing model is intentionally hierarchical. This makes routing more efficient. ISP’s receive large blocks, and every LAN uses a /64 subnet. Routers can provide huge ranges of addresses into a single route, making global routing tables even smaller. IPV6 keeps routing tables scalable as the internet grows.

	Another big deal game changer of IPV6 is how it opens the way for our world and everything in it to have an address of it’s own. IPV4’s addresses aren’t enough for the world and everything in it. IPV6’s  addressing architecture (RFC 4291) makes it easy to give every sensor, appliance, and things we can’t even imagine why would have to be connected at this point in time; that’s the beauty of it. There is so much addresses we don’t even need a reason why yet. This is exactly the type of planning that IPV4 failed to anticipate. IPV6’s /64 boundary and autoconfiguration make it possible for devices to join the network instantly without complicated setup. We may reach a point in the future when our contact lenses, socks, and pens or pencils want to talk on the cloud at the same time. Not only will IPV6 handle it effortlessly, we will still have a gargantuan addresses left over the rest of the stuff we can’t think of yet to get connectied . IPV4  simply can’t scale to that level without hacks, workarounds, and constant fixing.

	A big benefit in the world of IPV6 is that it doesn’t need to broadcast traffic. IPV4 needed to broadcast traffic. IPV4 uses ARP (Address Resolution Protocol). IPV6 replaces ARP with Neighbor Discover. The logic is this; You wouldn’t send a crew of 20 guys to fix a light switch, so why knock on every door in an entire network when we can just use end to end connectivity and keep all the collateral damage out of it. IPV6 can preserve the efforts of connections between indented source and destination packets. If we have that capability, then why not just organize all of our glorious connection sets logically, in order to systematically organize connections into groups. These groups can make the work of transporting a packet shorter and more efficient. We can literally cool down all the machinery of our systems and allow the circuits to work smarter and not harder. This is the beauty of multicasting. IPV6 doesn’t waste resources like IPV4 does when it uses broadcast methods. IPV6 makes machines’ networks happy by not frying them further by unnecessary broadcasts. Multicast replaces broadcast entirely.

	ICMP has beefed up and became a major component in the world of networking. It is essential to IPV6. It’s not just ping and traceroute anymore. ICMPV6 to be exact has opened up the world of Neighbor Discovery Protocol (NDP). ICMPV6 does address detection, neighbor reachability detection, redirect messaging, and Stateless Address Autoconfiguration, (SLAAC). SLAAC works harder to automate addresses and reduce complexity, improve communication, and simplify the world of networking. The days of DHCP and DORA should be behind us, although SARR doesn’t have nearly as cute and wholesome a mascot as DORA the explorer. The router advertisement provides a DNS prefix eliminating the need for DHCP, and as good as the DORA theme song is, that’s a win for networking, nonetheless.

	The IPV6 header is a good example of why we are allowed to trim out so much unnecessary overhead from classic networking. It is a fixed 40 bytes. It makes packet forwarding faster and easier. It doesn’t waste power configuring those bytes. It’s one less thing the algorithm needs to do; figuring out the length. Not only is DHCP not needed now; checksum and variable header lengths are gone. This is the type of overhead I mean that we don’t need anymore. We cut out the fluff and stick with the good stuff when we use IPV6. A fixed header length means every step counts towards efficiency. Optional features are handled through extension headers, which routers can skip unless needed. This means less work and more constructive connections. Connections such as error reporting, neighbor discovery, and path MTU discovery. 

	IPV6 handles multi-interface systems more gracefully than IPV4. IPV6 organizes address types for more efficient and productive networking. Link Local addresses are often the beginning of it all. They are automatically assigned and used for communication on the local network. Unique Local Addresses act like private IPV4 ranges. Global Unicast Addresses are routable on the internet. This clear separation of address types makes IPV6’s job easier to secure and clearer to understand. Windows requires a zone ID when using link-local addresses because multiple interfaces can share the same FE80 prefix, which is an important thing to note because it highlights that IPV6 is better with multi-interface systems. 
	In our Wireshark labs I was able to watch network behavior with IPV6. I was surprised how much was going one with Router Advertisements, Neighbor Solicitations, Neighbor Advertisements, all with ICMPv6 and not even needed a Wi-Fi connection. It is more easy to navigate and know what should be happening to assess problems and do the work more effectively.

	NAT is an opportunity for bad actors to infiltrate your network like cancer. NAT sets up a playground for hackers to infiltrate like snakes in the grass. The grass has been cut by IPV6 through the elimination of NAT and the fruition of total end to end connectivity. Nothing is perfect, but even though that might be, we also have some pretty cool tools from IPV6; like RA Guard that can block unauthorized Router Advertisements. DHCPv6 Guard can prevent rogue DHCP servers from influencing network behavior. We can validate redirect messages and ignore those from unauthorized sources. It is easier to apply consistent protections with IPV6 than it is to with IPV4.

	IPV6 is the clear choice for the future of networking. IPV4 is too stubborn to let it have it change though. It might not be replaced for many generations. Many networks are dual-stack configured. So for the time being; both IPV4 and IPV6 traffic are just going to have to run at the same time. Tunneling mechanisms like 6to4 and ISATAP were created to help IPV6 move its packets through IPV4 virtual cobwebs, and NAT64 allows IPV6 only devices to communicate with IPV4 servers. These transition tools are described in RFC 4213 and exists only to keep IPV4 alive and pumping. They are only in place to keep the internet moving without the total confusion resulting from left over IPV4 technology. The fact that we need these things is an annoying reminder of why IPV4 is something that’s not so easy to get rid of.

The many reasons to switch over to IPV6 should make it a no brainer. IPV6 simplifies routing, eliminates NAT, scales globally, and is more efficient for modern hardware. It eliminates decades of bad IPV4 baggage. IPv6’s /64 boundary is intentionally designed to simplify addressing and support SLAAC. You get all these new capabilities automatically. It’s so smooth that devices could now literally configure themselves. It’s direct end to end communication. It preserves resources and improves efficiency. It opens the doors to an internet of things, not just old clunky devices. IPV6 is the future whether you like it or not. I know now how to be an IPV6 evangelist so the next time someone whines about how their existing infrastructure is good enough, I can tell them in full confidence that they don’t know what they are talking about. It’s time to go forward and let the world know; IPV4 has got to go!
 `
};
  

class August32026 extends Component {
  
    render(){
    return (
      <div style={blogContent} className="February7">
      <p>
{blogContent.content}
      </p>
      </div>
    );
  }
}


export default August32026;